In [1]:
from sympy import *
from scipy.optimize import fsolve
import numpy as np

In [60]:
# define system matrix with boundary and transition conditions

k = symbols("k")

l = 12.5

A_full = Matrix([[1, 0, 1, 0, 0, 0, 0, 0],
            [1, 0, -1, 0, 0, 0, 0, 0],
            [0, sinh(k*l), 0, -sin(k*l), 0, 0, 0, 0,],
            [0, 0, 0, 0, 1, 0, 1, 0],
            [0, cosh(k*l), 0, -cos(k*l), 0, -1, 0, 1],
            [0, -sinh(k*l), 0, -sin(k*l), 1, 0, -1, 0],
            [0, 0, 0, 0, cosh(k*l), sinh(k*l), cos(k*l), -sin(k*l)],
            [0, 0, 0, 0, cosh(k*l), sinh(k*l), -cos(k*l), sin(k*l)]])

A = Matrix([[sinh(k*l), -sin(k*l), 0, 0, 0, 0,],
            [ 0, 0, 1, 0, 1, 0],
            [cosh(k*l), -cos(k*l), 0, -1, 0,1],
            [-sinh(k*l), -sin(k*l), 1, 0, -1, 0],
            [0, 0, cosh(k*l), sinh(k*l), cos(k*l), -sin(k*l)],
            [0, 0, cosh(k*l), sinh(k*l), -cos(k*l), sin(k*l)]])



In [64]:
det_A = det(A)
det_A

-8*sin(12.5*k)**2*sinh(12.5*k)*cosh(12.5*k) + 8*sin(12.5*k)*cos(12.5*k)*sinh(12.5*k)**2

In [ ]:
k_values = roots(det_A, k, 1.0)
k_values

In [65]:
lam_f = lambdify(k, det_A)

In [73]:


#sol = fsolve(lam_f, bracket=[0.1,15])
sol = fsolve(lam_f, 0.23, xtol=1.49012e-12)
sol 

array([0.25132741])

In [79]:
# eigenfrequencies

I = 0.6**3*0.1/12 # m^3
EI = I * 3e10 
mu = 0.6*0.1*2000

eigenfreq_list = []

for j in range(1,4):

    cur_val = (j*0.2513274123)**4*EI/mu #0.2513274123

    eigenfreq_list.append(np.sqrt(cur_val)/2/np.pi)

    
eigenfreq_list


[np.float64(6.743822142486906),
 np.float64(26.975288569947622),
 np.float64(60.694399282382136)]

In [82]:
def func(x):

    return -8*np.sin(l*x)*np.cosh(l*x)+8*np.cos(l*x)*np.sinh(l*x)

In [92]:
sol2 = fsolve(func, 0.45, xtol=1.49012e-12)
sol2

array([0.31412818])

In [1]:
shapes = np.loadtxt("Job-1_modes.dat")

NameError: name 'np' is not defined

In [94]:
import matplotlib.pyplot as plt



In [103]:
shapes.shape

(120, 10)

In [104]:
shapes = np.transpose(shapes)

In [105]:
shapes[0:5,0:5]

array([[-2.78336571e-04, -8.96996043e-04,  4.88691913e-05,
        -8.72830031e-04,  3.54674284e-04],
       [-2.73871605e-04, -1.00313315e-03,  8.82063349e-05,
        -9.78985823e-04,  4.26499513e-04],
       [ 4.60102248e-04,  2.49413210e-03, -3.86759612e-04,
         2.45352715e-03, -1.16382159e-03],
       [ 5.55936917e-04,  2.54675690e-03, -3.11503116e-04,
         2.49915840e-03, -1.10501629e-03],
       [-9.14098275e-04, -4.14100588e-03,  4.28903055e-04,
        -4.06797782e-03,  1.62652933e-03]])